# Generated by Django 4.1.6 on 2023-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('default', 'همکار ارجمند'), ('sir', 'آقای'), ('madam', 'خانم')], default='default', max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('organizationalUnit', models.CharField(max_length=50)),
                ('floorUnit', models.CharField(max_length=50)),
                ('organizationPhone', models.CharField(max_length=3)),
                ('directPhone', models.CharField(max_length=8)),
            ],
        ),
    ]
